<!-- Intro message -->
<div class="jumbotron">
	<h1>Your Jobs</h1>

	<p>Configure some jobs whenever you get a chance. No rush.</p>
</div>

<?php foreach ($this->get('jobsHelper')->getJobs() as $key => $job) : ?>
	<h2 id="#<?php echo $key; ?>"><?php echo $job->name; ?></h2>
	<p>Marshmallow gingerbread tootsie roll chocolate bar lollipop. Sweet jelly caramels danish. Sweet roll chocolate
		cake muffin. Biscuit dragée topping sweet ice cream. Jujubes chocolate sweet dessert marzipan. Muffin pastry
		muffin topping biscuit biscuit powder. Biscuit powder sugar plum sugar plum soufflé cupcake lollipop. Sweet
		dessert candy wafer gummi bears icing icing lemon drops. Cake pie bonbon chocolate cake toffee I love dragée.
		Candy biscuit sweet macaroon. Candy applicake tiramisu tiramisu unerdwear.com marshmallow I love sesame snaps.
		Sugar plum sweet roll bear claw chocolate cake chocolate apple pie liquorice candy canes. Tiramisu I love I love
		chocolate. Chocolate cake jelly beans I love danish muffin chocolate cake muffin.</p>
	<p>Marshmallow gingerbread tootsie roll chocolate bar lollipop. Sweet jelly caramels danish. Sweet roll chocolate
		cake muffin. Biscuit dragée topping sweet ice cream. Jujubes chocolate sweet dessert marzipan. Muffin pastry
		muffin topping biscuit biscuit powder. Biscuit powder sugar plum sugar plum soufflé cupcake lollipop. Sweet
		dessert candy wafer gummi bears icing icing lemon drops. Cake pie bonbon chocolate cake toffee I love dragée.
		Candy biscuit sweet macaroon. Candy applicake tiramisu tiramisu unerdwear.com marshmallow I love sesame snaps.
		Sugar plum sweet roll bear claw chocolate cake chocolate apple pie liquorice candy canes. Tiramisu I love I love
		chocolate. Chocolate cake jelly beans I love danish muffin chocolate cake muffin.</p>
	<p>Marshmallow gingerbread tootsie roll chocolate bar lollipop. Sweet jelly caramels danish. Sweet roll chocolate
		cake muffin. Biscuit dragée topping sweet ice cream. Jujubes chocolate sweet dessert marzipan. Muffin pastry
		muffin topping biscuit biscuit powder. Biscuit powder sugar plum sugar plum soufflé cupcake lollipop. Sweet
		dessert candy wafer gummi bears icing icing lemon drops. Cake pie bonbon chocolate cake toffee I love dragée.
		Candy biscuit sweet macaroon. Candy applicake tiramisu tiramisu unerdwear.com marshmallow I love sesame snaps.
		Sugar plum sweet roll bear claw chocolate cake chocolate apple pie liquorice candy canes. Tiramisu I love I love
		chocolate. Chocolate cake jelly beans I love danish muffin chocolate cake muffin.</p>
	<p>Marshmallow gingerbread tootsie roll chocolate bar lollipop. Sweet jelly caramels danish. Sweet roll chocolate
		cake muffin. Biscuit dragée topping sweet ice cream. Jujubes chocolate sweet dessert marzipan. Muffin pastry
		muffin topping biscuit biscuit powder. Biscuit powder sugar plum sugar plum soufflé cupcake lollipop. Sweet
		dessert candy wafer gummi bears icing icing lemon drops. Cake pie bonbon chocolate cake toffee I love dragée.
		Candy biscuit sweet macaroon. Candy applicake tiramisu tiramisu unerdwear.com marshmallow I love sesame snaps.
		Sugar plum sweet roll bear claw chocolate cake chocolate apple pie liquorice candy canes. Tiramisu I love I love
		chocolate. Chocolate cake jelly beans I love danish muffin chocolate cake muffin.</p>
<?php endforeach; ?>
