<?php $this->render('header'); ?>
		<!-- Intro message -->
		<div class="jumbotron">
			<h1><span class="label label-success">100%</span> is your current success rate.</h1>
			<p class="lead">
				Marvel in this bird's eye view of all of your configured jobs.<br />
				Build, test, deploy, enjoy.
			</p>
		</div>

		<!-- Nav tabs -->
		<ul id="dashboard-tabs" class="nav nav-tabs nav-justified">
			<li class="active"><a href="#recent-jobs" data-toggle="tab" class="text-muted"><span class="glyphicon glyphicon-time"></span> Recent Jobs <span class="badge pull-right">10</span></a></li>
			<li><a href="#queue" data-toggle="tab" class="text-muted"><span class="glyphicon glyphicon-pushpin"></span> Job Queue <span class="badge pull-right">0</span></a></li>
			<li><a href="#failures" data-toggle="tab" class="text-danger"><span class="glyphicon glyphicon-ban-circle"></span> Failures <span class="badge pull-right">3</span></a></li>
		</ul>

		<!-- Tab panes -->
		<div id="dashboard-views" class="tab-content">
			<div class="tab-pane active" id="recent-jobs">
				<table class="table table-striped">
					<tr>
						<th>Job #</th>
						<th>Job Name</th>
						<th>Project</th>
						<th>Status</th>
						<th colspan="2">Notes</th>
					</tr>
					<?php for($i=0; $i<10; $i++) : ?>
					<tr>
						<td><?php echo (10-$i); ?></td>
						<td>Build and Test</td>
						<td><strong class="project-title"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-new-window"></span> griasolutions/gria-lib</button></td>
						<td><span class="label label-success">All love, son!</span></td>
						<td>Triggered by commit <code>9043as213d33</code> 2 minutes ago<br/><small>Build ran in 30 seconds. Took a bit long, no?</small></td>
						<td>
							<div class="btn-group btn-group">
								<button type="button" class="btn btn-default btn-primary"><span class="glyphicon glyphicon-play-circle"></span> Run</button>
								<button type="button" class="btn btn-default btn-info" data-toggle="modal" data-target="#log-modal"><span class="glyphicon glyphicon-info-sign"></span> View Reports</button>
							</div>
						</td>
					</tr>
					<?php endfor; ?>
				</table>
			</div>
			<div class="tab-pane" id="queue">
				<table class="table table-striped">
					<tr>
						<th>Job #</th>
						<th>Job Name</th>
						<th>Project</th>
						<th colspan="2">Notes</th>
					</tr>
					<?php for($i=0; $i<10; $i++) : ?>
						<tr>
							<td><?php echo (10-$i); ?></td>
							<td>Build and Test</td>
							<td><strong class="project-title"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-new-window"></span> griasolutions/gria-lib</button></td>
							<td>Triggered by commit <code>9043as213d33</code> 2 minutes ago<br/><small>Build ran in 30 seconds. Took a bit long, no?</small></td>
							<td><button type="button" class="btn btn-default btn-danger"><span class="glyphicon glyphicon-minus-sign"></span> Dequeue</button></td>
						</tr>
					<?php endfor; ?>
				</table>
			</div>
			<div class="tab-pane" id="failures">
				<table class="table table-striped">
					<tr>
						<th>Job #</th>
						<th>Job Name</th>
						<th>Project</th>
						<th colspan="2">Notes</th>
					</tr>
					<?php for($i=0; $i<10; $i++) : ?>
						<tr>
							<td><?php echo (10-$i); ?></td>
							<td>Build and Test</td>
							<td><strong class="project-title"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-new-window"></span> griasolutions/gria-ci</button></td>
							<td>Triggered by commit <code>9043as213d33</code> 2 minutes ago<br/><small>Build ran in 30 seconds. Took a bit long, no?</small></td>
							<td>
								<div class="btn-group btn-group">
									<button type="button" class="btn btn-default btn-primary"><span class="glyphicon glyphicon-play-circle"></span> Run</button>
									<button type="button" class="btn btn-default btn-info" data-toggle="modal" data-target="#log-modal"><span class="glyphicon glyphicon-info-sign"></span> View Reports</button>
								</div>
							</td>
						</tr>
					<?php endfor; ?>
				</table>
			</div>
		</div>
	</div>
</div>

<?php $this->render('reports-modal'); ?>
<?php $this->render('footer'); ?>

