<?php echo $this->renderPartial('header'); ?>

<?php echo $this->renderPartial('error/' . $this->get('exception')->getCode()); ?>

<?php if (ini_get('display_errors')) : ?>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<div class="panel-title">
				<strong>Error</strong>: <?php echo $this->get('exception')->getMessage(); ?>
			</div>
		</div>
		<div class="panel-body">
			<p><?php echo nl2br($this->get('exception')->getTraceAsString()); ?></p>
		</div>
	</div>
<?php endif; ?>


<?php echo $this->renderPartial('footer'); ?>

