<?php $jobs = (new \GriaCi\Helper\Job($this->getConfig()))->getJobs(); ?>

<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Gria/<strong>CI</strong></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li<?php echo($this->getRequest()->getControllerName() == 'dashboard' ? ' class="active"' : ''); ?>>
					<a href="/dashboard">Dashboard</a>
				</li>
				<li<?php echo($this->getRequest()->getControllerName() == 'about' ? ' class="active"' : ''); ?>>
					<a href="/about">About</a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span
							class="glyphicon glyphicon-cog"></span> Settings <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="#">Download recent logs</a></li>
						<li class="divider"></li>
						<li class="dropdown-header">Projects</li>
						<?php foreach ($jobs as $key => $job) : ?>
							<li><a href="/jobs#<?php echo $key; ?>"><?php echo $job->name; ?></a></li>
						<?php endforeach; ?>
					</ul>
				</li>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
</div>